name: BlazeDemo CI CI Workflow Pipelines
on: [push]
jobs:
  BlazeDemo_cypress_chrome_test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 
      - name: Cypress.io
        uses: cypress-io/github-action@v6.10.2
        with:
          start: npm run cypress:run:chrome